Global:
  device: cuda
  resume_training: False

Optimizer:
  lr: 0.0005

Train:
  dataset:
    name: cidar15
    image_dir: dataset/icdar2015/train/images
    anno_dir: dataset/icdar2015/train/gt
    ignore_tags: ['*', '###']
    transforms:
      image_shape: [3, 640, 640]
      augmentation: True
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

  loader:
    epochs: 20
    eval_step: 1
    shuffle: True
    batch_size: 256
    num_workers: 4
    use_shared_memory: False

  checkpoint:
    last_path: weights/last.pth
    best_path: weights/best.pth

Eval:
  dataset:
    name: cidar15
    image_dir: dataset/icdar2015/test/images
    anno_dir: dataset/icdar2015/test/gt
    ignore_tags: ['*', '###']
    transforms:
      image_shape: [3, 640, 640]
      augmentation: False
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

  loader:
    shuffle: False
    batch_size: 128
    num_workers: 4
    use_shared_memory: False

Debug:
  transforms: debugs/transformation
  log_file: 'logs/crnn.log'
  tensorboard: debugs/tensorboard
  dataset: 'debugs/dataset'
  label_generation: 'debugs/label_generation'
  validate_polygons: 'debugs/validate_polygons'