Global:
  device: cuda
  resume_training: False

Optimizer:
  lr: 0.001

Train:
  dataset:
    name: cidar15
    image_dir: dataset/total_text/train_images
    anno_dir: dataset/total_text/train_gts
    ignore_tags: ['*', '###']
    transforms:
      image_shape: [3, 736, 736]
      augmentation: True
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

  loader:
    epochs: 200
    eval_step: 1
    shuffle: True
    batch_size: 6
    num_workers: 4
    use_shared_memory: False

  checkpoint:
    last_path: weights/last.pth
    best_path: weights/best.pth

Eval:
  dataset:
    name: cidar15
    image_dir: dataset/total_text/test_images
    anno_dir: dataset/total_text/test_gts
    ignore_tags: ['*', '###']
    transforms:
      image_shape: [3, 736, 736]
      augmentation: False
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

  loader:
    shuffle: False
    batch_size: 2
    num_workers: 4
    use_shared_memory: False

Debug:
  transforms: debugs/transformation
  log_dir: 'logs/'
  tensorboard: debugs/tensorboard
  dataset: 'debugs/dataset'
  label_generation: 'debugs/label_generation'
  validate_polygons: 'debugs/validate_polygons'
  prediction: 'outputs'
  model: debugs/model
  